### ISSUE TITLE
Benchmark SlimFast and Ruby Slim

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#47]
I think it would be interesting to compare SlimFast and the original Slim implementation.  Putting together a simple benchmark could be fun.

**Comment by henrik** [comment]
Made a start of this here: https://github.com/henrik/slim_fast_benchmarks

It's not complete and does not run Ruby Slim. Just intended as a beginning.

Mostly because I was curious about how to set it up. Added you as a collaborator, @doomspork. You know more about the library – please feel free to change it, move the repo etc. Not sure if I'll spend more time on it, at least not for a while.

**Comment by henrik** [comment]
And if you want to bench it in a different way (maybe this setup is not a good way to test slim_fast and Ruby Slim against each other), don't feel that you have to use my code at all. Just wanted to look into Elixir benching a little :)

**Comment by doomspork** [comment]
This is great @henrik, thank you!  I haven't used benchmarking in Elixir yet so this is a great start.  I'll try to set aside some time to pull this down and play with it.

**Comment by lpil** [comment]
I think benchmarking against Ruby slim is kind of pointless. I'd be more interested against benchmarks against other Elixir template engines, such as `eex`, something that does haml, etc.

**Comment by doomspork** [comment]
The benchmarking was always for fun.  When the original goal was to create an official Slim implementation it would have been neat to see how they compared.

**Comment by henrik** [comment]
That is a very good point. Also easier to do… :)
