### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#55]
Should we rename the project? It's similar but not identical to Ruby Slim.

Earlier discussion: https://github.com/doomspork/slim_fast/pull/54#issuecomment-154556365

**Comment by doomspork** [comment]
There are two topics of discussion, right?  The first being whether we deviate from the official Slim standard like Jade and the second being a possible name change.

I'm really fascinated by your suggestion RE: Jade, it opens up a lot of possibilities.  There may be things specific to Elixir that would make sense being included in concise markup such as this.  For me this is particularly exciting.  I'm anxious to hear from @Rakoth and @joakimk.

Initially I'm :-1: on the name change because I'm not sure what purpose it serves.  That said if there's something that everyone is excited about I'm certainly open to the idea.

**Comment by henrik** [comment]
Yeah, you could definitely see it as two questions.

The idea of possibly breaking away further from Ruby Slim is inspired a lot by @joakimk's idea that we could reimagine what a Slim-like language might look like if it was written for Elixir to begin with.

About the name change, my thinking is that it could help set expectations. I was a bit confused initially by something called "Slim" (well, "SlimFast") not working just like Ruby Slim – the fact that `- if foo` didn't work and so on. I've later come to realize that Ruby Slim is so coupled to Ruby that we couldn't reasonably match it exactly – but if we don't, a name change could also signal that this is not your father's Slim. "SlimFast" suggests it _is_ Slim but faster.

**Comment by henrik** [comment]
…but I don't feel very strongly about the name change. If we decide to stick with something close to Ruby Slim, with only minor language-related differences, I could definitely see us sticking with this name. Especially now that these differences are much clearer in the README.

**Comment by joakimk** [comment]
I like the idea of a name change. Keep "Slim-like" in the salespitch (if nothing else for googleability), but document what this template format can do rather than what's different from slim. That way we could start small and increase the number of features as we go (as they are needed) and not feel like we're fightning to catch up with slim.

A 1.0 of an elixir slim-like template format, a stable version with few, but well implemented, bugfree and documented features. That's worth a lot and is achievable in a reasonable amount of time. It would signal that it's ready to use and you know what you get.

A 1.0 of a elixir slim would be very hard to achieve if it's supposed to be fully API compatible with ruby slim, so it will be forever o-point-something, and won't get the benefit of the above.

**Comment by doomspork** [comment]
Good point about 1.0 @joakimk, I think makes a lot of sense.

Ha! @henrik I honestly hadn't thought about "Slim but faster" until now.  The name is from a weight loss shake that was popular in the US in the 90s.  I was actually trying to come up with a name that would stick with an "elixir" theme.  The "Slim" portion was a bonus.

:+1: I'm on board with brainstorming some new names.

**Comment by henrik** [comment]
Haha, oh, didn't get that reference at all I'm afraid :D Clever!

**Comment by joakimk** [comment]
Maybe something related to printing information, like "scroll" or "tome".

I like "tome", 4 characters and easy to spell: slim tome jade haml.

**Comment by lpil** [comment]
I support a name change as it will reduce confusion over the syntactic differences between Ruby slim and this one.

**Comment by doomspork** [comment]
@joakimk I like the idea of using a shorter name.

Couple quick ideas:
- Drip
- Mex (Minimal Eex)

Any other suggestions?  I'll try to think of a few more and we can pull them together and figure out what works best.

Thanks everyone :+1:!

**Comment by henrik** [comment]
I still kind of like "Slime". It's liquid(ish) like an elixir, and is reminiscent of "Slim". But maybe too similar.

**Comment by joakimk** [comment]
So then you've got slime all over your web application... :+1:

Best so far I think (no particular order): "slime", "mex", "tome".

**Comment by lpil** [comment]
I quite like Scroll, as suggested by Joakimk.

Slime makes me think of emacs SLIME and vim-slime.

**Comment by lpil** [comment]
Have we made a decision? @doomspork, as the projects benevolent dictator why not just pick something? :)

**Comment by doomspork** [comment]
Hi @lpil, thanks for the note.  I can certainly pick a name but I wanted to let everyone have a chance to cast a vote :grinning:

**Comment by joakimk** [comment]
Put up a vote somewhere and link it here?

**Comment by lpil** [comment]
I'll also vote with @henrik and @joakimk in favour of Slime.

**Comment by doomspork** [comment]
Slime it is.  @lpil and I are going to move everything over.  Also created a GitHub org for slime-lang.  Transferred over slim_fast, phoenix_slim, and phoenix_slim_example.
